# Generated by Django 2.2.3 on 2019-11-05 17:42

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre.', max_length=40)),
                ('apellido', models.CharField(help_text='Ingrese el apellido.', max_length=40)),
                ('hora_1_inicio', models.TimeField(blank=True, help_text='Ingrese el inicio de la primera hora.', null=True, verbose_name='Desde')),
                ('hora_1_fin', models.TimeField(blank=True, help_text='Ingrese el fin de la primera hora.', null=True, verbose_name='Hasta')),
                ('hora_2_inicio', models.TimeField(blank=True, help_text='Ingrese el inicio de la segunda hora.', null=True, verbose_name='Desde')),
                ('hora_2_fin', models.TimeField(blank=True, help_text='Ingrese el fin de la segunda hora.', null=True, verbose_name='Hasta')),
                ('hora_3_inicio', models.TimeField(blank=True, help_text='Ingrese el inicio de la tercer hora.', null=True, verbose_name='Desde')),
                ('hora_3_fin', models.TimeField(blank=True, help_text='Ingrese el fin de la tercer hora.', null=True, verbose_name='Hasta')),
                ('hora_4_inicio', models.TimeField(blank=True, help_text='Ingrese el inicio de la cuarta hora.', null=True, verbose_name='Desde')),
                ('hora_4_fin', models.TimeField(blank=True, help_text='Ingrese el fin de la cuarta hora.', null=True, verbose_name='Hasta')),
                ('hora_5_inicio', models.TimeField(blank=True, help_text='Ingrese el inicio de la quinta hora.', null=True, verbose_name='Desde')),
                ('hora_5_fin', models.TimeField(blank=True, help_text='Ingrese el fin de la quinta hora.', null=True, verbose_name='Hasta')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Obligatorio', max_length=50)),
                ('texto', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, help_text='Opcional', null=True, upload_to='asesoria/novedades')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese su nombre.', max_length=20)),
                ('apellido', models.CharField(help_text='Ingrese su apellido.', max_length=20)),
                ('horario', models.TimeField(help_text='Ingrese el horario que tenga disponible.')),
                ('motivo', models.CharField(choices=[('Escolar', 'Escolar'), ('Personal', 'Personal')], default='Escolar', help_text='Ingrese aquí el motivo.', max_length=8)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(help_text='Ingrese su teléfono.', max_length=128, region='AR', verbose_name='Teléfono')),
                ('email', models.EmailField(help_text='Ingrese aquí su email.', max_length=254)),
                ('nota', models.TextField(blank=True, help_text='(*Opcional.)')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
    ]
